fx_version 'adamant'
game 'gta5'

files {
    'audioconfig/*.dat151.rel',
    'audioconfig/*.dat54.rel',
    "audioconfig/*.dat10.rel",
    'sfx/**/*.awc'
}

dependencies {
    'mp-importvehicles'
}

data_file 'AUDIO_GAMEDATA' 'audioconfig/aventadorv12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aventadorv12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aventadorv12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bcat_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cvpiv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cvpiv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cvpiv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cw2019_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cw2019'
data_file 'AUDIO_GAMEDATA' 'audioconfig/dilettantedx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/dilettantedx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_dilettantedx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f10m5_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f10m5_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f10m5'
data_file 'AUDIO_GAMEDATA' 'audioconfig/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s85b50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/dlcsavanna_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sentinelsg4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/skart_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/skart_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_skart'
data_file 'AUDIO_GAMEDATA' 'audioconfig/stratumc_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_zircoflow'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq10nisvr38dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq10nisvr38dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq10nisvr38dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m113k_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m113k_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m113k'
data_file "AUDIO_SYNTHDATA" "audioconfig/dghmieng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/dghmieng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/dghmieng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_dghmieng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/n4g63t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n4g63t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n4g63t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq26mit4b11t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq26mit4b11t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq26mit4b11t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq22honb18c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq22honb18c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq22honb18c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq03ej257_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq03ej257_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq03ej257'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq05ej257el_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq05ej257el_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq05ej257el'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq21honb16a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq21honb16a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq21honb16a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqtoy2jzstock_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqtoy2jzstock_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqtoy2jzstock'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq2jzgterace_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq2jzgterace_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq2jzgterace'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ecoboostv6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mrtasty_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mrtasty_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mrtasty'
data_file 'AUDIO_GAMEDATA' 'audioconfig/turismoc_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/turismoc_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_turismoc'